apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  MONGO_URL: "mongodb://mongo-service:27017/holidays"
  MYSQL_DB: "travel"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  MYSQL_USER: "user"
  MYSQL_PASSWORD: "pass123"
  MYSQL_ROOT_PASSWORD: "rootpass"
