apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2025-09-01T04:10:53Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2025-09-01T05:21:59Z"
  labels:
    app: holiday-db
  name: mongo-data-holiday-db-0
  namespace: default
  resourceVersion: "7230"
  uid: e162ec79-f038-4bdf-b1d7-b439390cc3a1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: holiday-db-pv-2
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  phase: Bound
