apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: travel-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    # Rewrite so backend receives correct path
    #nginx.ingress.kubernetes.io/rewrite-target: / #changed from $2 to /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # Frontend (root app)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: travel-frontend-service
            port:
              number: 80

